export default {
    inside: 'Inside',
    outside: 'Outside',
    publicTransport: 'public transport',
    privateCar: 'private car',
    publicBuilding: 'public building',
    residential: 'residential',
    privateBuildingNonResidential: 'private building non-res.',
    privatePropertyResidential: 'private property - residential',
    onTheStreet: 'on the street',
    publicPark: 'public park',
    privatePropertyNonResidential: 'private property non-res.',
    other: 'other',
    age: 'Age',
    ageWarning: 'Please enter a valid age.',
    gender: 'Gender',
    genderWarning: 'Please make a selection.',
    zipCode: 'Zipcode',
    zipCodeWarning: 'This field cannot be empty.',
    createDemographic: 'create demographic',
    formIsWalidWarning: 'Wrong Input',
    formIsWalidWarningText: 'Please check the errors in the form.',
    verySafe: 'Very Safe',
    safe: 'Safe',
    safeUnsafe: 'Neither Safe nor Unsafe',
    unsafe: 'Unsafe',
    veryUnsafe: 'Very Unsafe',
    emergencyText: '*** If you are in danger call 911 immediately ***',
    male: 'Male',
    female: 'Female',
    transMale: 'Trans Male',
    transFemale: 'Trans Female',
    surveyQuestion: 'In terms of physical safety, how safe do you feel right now?',
    okay: 'Okay',
    question: 'More specifically, where ${location} are you?',
    finish: 'Finish Survey',
    signUp: 'Signup',
    email: 'Email',
    verifyEmail: 'Verify Email',
    emailWarning: 'Please enter a valid email',
    locationQuestion: 'Where are you right now?',
    splashText: 'To finish logging in, please complete these three easy steps: ' +
        '\n\n1. Go to your email from your phone ' +
        '\n\n2. Locate the verification email' +
        '\n\n3. Click the log-in link provided',
    thankYouText: 'Thank you for your participation.',
    welcomeScreenText: 'This is a research tool created by the development team to ' +
        'better understand how personal security concerns are influenced by private and public spaces. ' +
        'We collect and store demographic and response data. ' +
        '\n\nWe DO NOT store any personal data. ' +
        '\n\nPlease contact us with any questions or concerns.',
    startNewSurvey:'Start New Survey',
    notificationText: 'Hi there! Feeling alright? Tap to record your response.',
}
